# Generated by Django 3.1.4 on 2021-09-01 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
