# Generated by Django 3.1.4 on 2021-09-27 10:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210927_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(null=True, upload_to=core.models.user_image_file_path),
        ),
    ]
